export const USER_ROUTES = {
  HOME: "/home",
  PREVIEW: "/preview",
  OUR_BLOGS: "/blogs",
  TEMPLET_EDITORS: "/templet",
  TEMPLET_EDITORS_PREVIEW: "/templet-preview",
  CATEGORIES_EDITORS_PREVIEW: "/categories-preview",
  OUR_BLOGS_DETAILS: "/blogs-details",
  OUR_SUSTAIANIBILITY: "/sustainability",
  VIEW_ALL: "/view-all",
  USER_DRAFTS_CARDS: "/drafts",
  ADD_TO_CART: "add-to-cart",
  COMMUNITY_HUB: "/community-hub",
  SUBSCRIPTION: "/subscription",
  SUCCESS_PAY: "/success-payment",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  USER_PROFILE: "/profile",
};

export const ADMINS_DASHBOARD = {
  SIGNIN: "/admin-signin",
  HOME: "/dashboard",
  CUSTOMERS: "/customers",
  PRODUCTS_LIST: "/products",
  ORDERS_LIST: "/orders",
  ADD_NEW_CARDS: "/add-new-cards",
  ADD_NEW_TEMPLETS_CARDS: "/add-new-templets",
  ADD_CATEGORY: "/add-categories",
  ADMIN_EDITOR: "/admin-editor",
  ADMIN_CATEGORIES_EDITOR: "/categories-editor",
  ADMIN_CATEGORIES_EDITOR_PREIVEW: "/categories-editor-preivew",
  ADMIN_CATEGORIES: "/admin-category",
  ADMIN_BLOGS: "/admin-blogs",
  ADMIN_BLOGS_EDITOR: "/admin-blogs-editor",
  ADMIN_TOTURIAL_GUIDE: "/admin-toturial-guide",
  ADMIN_COMMUNITY_HUB: "/admin-community-hub",
  ADD_COMMUNITY_HUB_POST: "/add-community-hub-post",
  ADMIN_REPORTS: "/admin-reports",
  SETTINGS: "/setting",
};
